#pragma once

#define _SYS_async_pulse 1
#define _SYS_async_poll 2
#define _SYS_async_listen 3
#define _SYS_nbsend 4
#define _SYS_send 5
#define _SYS_call 6
#define _SYS_recv 7
#define _SYS_reply 8
#define _SYS_hello 9
#define _SYS_print 10
#define _SYS_con_putchar 11
#define _SYS_con_write 12
#define _SYS_halt 13
#define _SYS_rt_new 14
#define _SYS_rt_open 15
#define _SYS_rt_check 16
#define _SYS_rt_delete 17
#define _SYS_rt_revoke 18
#define _SYS_exit 19
#define _SYS_getpid 20
#define _SYS_sched_next 21
#define _SYS_softirq_done 22
#define _SYS_softirq_set_enable 23
#define _SYS_thread_check 24
#define _SYS_thread_suspend 25
#define _SYS_thread_active 26
#define _SYS_thread_set_register 27
#define _SYS_thread_set_priority 28
#define _SYS_thread_get_priority 29
#define _SYS_thread_get_state 30
