#pragma once

#define _SYS_async_pulse 1
#define _SYS_async_poll 2
#define _SYS_async_listen 3
#define _SYS_nbsend 4
#define _SYS_send 5
#define _SYS_call 6
#define _SYS_recv 7
#define _SYS_hello 8
#define _SYS_putchar 9
#define _SYS_print 10
#define _SYS_halt 11
#define _SYS_rt_new 12
#define _SYS_rt_open 13
#define _SYS_rt_check 14
#define _SYS_rt_delete 15
#define _SYS_rt_revoke 16
#define _SYS_exit 17
#define _SYS_getpid 18
#define _SYS_sched_next 19
#define _SYS_softirq_done 20
#define _SYS_softirq_set_enable 21
#define _SYS_thread_check 22
#define _SYS_thread_suspend 23
#define _SYS_thread_active 24
#define _SYS_thread_set_register 25
#define _SYS_thread_set_priority 26
#define _SYS_thread_get_priority 27
#define _SYS_thread_get_state 28
