#pragma once

#define _SYS_exit 1
#define _SYS_getpid 2
#define _SYS_sched_next 3
#define _SYS_rt_new 4
#define _SYS_rt_check 5
#define _SYS_rt_delete 6
#define _SYS_rt_revoke 7
#define _SYS_softirq_done 8
#define _SYS_softirq_set_enable 9
#define _SYS_nbsend 10
#define _SYS_send 11
#define _SYS_call 12
#define _SYS_recv 13
#define _SYS_thread_check 14
#define _SYS_thread_suspend 15
#define _SYS_thread_active 16
#define _SYS_thread_set_register 17
#define _SYS_thread_set_priority 18
#define _SYS_thread_get_priority 19
#define _SYS_thread_get_state 20
#define _SYS_async_pulse 21
#define _SYS_async_poll 22
#define _SYS_async_listen 23
#define _SYS_hello 24
#define _SYS_putchar 25
#define _SYS_print 26
#define _SYS_halt 27
