# automaticly generated by scripts/config.sh
PLAT=i386
ARCH=x86
BITS=32
ROOT="C:\Users\Lenovo\Intel\OSD\Cygwin\home\Lenovo\dev\h2os"
QEMU="C:\Users\Lenovo\Intel\OSD\QEMU\qemu-system-i386w.exe"
MINGW=1
NODEP=1
